// cSpell:ignore codenarc groovylintrc javadoc nvuillam println sandboxed shellenv
= Groovy & Groovy Linting

== Introduction
Limitations Inherent to Groovy::
* Groovy is not memory safe and not (run-time) type safe.

Limitations of Hubitat's _Sandboxed_ Environment::
* Imports are limited (see https://docs2.hubitat.com/en/developer/allowed-imports[Allowed Imports])
* Some Groovy methods have Hubitat alternatives:
** `println()` → `log.trace()`, `logDebug()`, `logInfo()`, `logWarn()`, `logError()`
** `sleep()` → `pauseExecution()`
* Custom classes, custom JARs and thread creation are not possible (see https://docs2.hubitat.com/en/developer/overview[Developer Overview]).
* Class-like instances can be simulated (see https://TBD[Class-Like Constructs])

Groovy Linting in Hubitat::
* Linting is possible with adjustments for Hubitat's _sandboxed_ environment.
* Some issues have been reported with the `nvuillam / vscode-groovy-lint` (vscode-groovy-lint) extension. The issues *may* be more significant when using `code-server` and/or using a multi-repo workspace.

== Linting Adjustments for Hubitat's Sandbox
The following adjustments are relative to https://github.com/nvuillam/npm-groovy-lint/blob/14e2649ff7ca642dba3e901c17252b178bea8b1b/.groovylintrc.json[`nvuillam/npm-groovy-lint/.groovylintrc.json`].

.Initial `.groovylintrc.json`
```
{
  "extends": "recommended",
  "rules": {
    "CatchException": {
      "enabled": false
    },
    "CatchThrowable": {
      "enabled": false
    },
    "ClassJavadoc": {
      "enabled": false
    },
    "ClosureAsLastMethodParameter": {
      "enabled": false
    },
    "DuplicateNumberLiteral": {
      "enabled": false
    },
    "DuplicateStringLiteral": {
      "enabled": false
    },
    "FieldTypeRequired": {
      "enabled": false
    },
    "JavaIoPackageAccess": {
      "enabled": false
    },
    "MethodParameterTypeRequired": {
      "enabled": false
    },
    "MethodSize": {
      "enabled": false
    },
    "NoDef": {
      "enabled": false
    },
    "PrintStackTrace": {
      "enabled": false
    },
    "PropertyName": {
      "enabled": false
    },
    "SpaceAroundMapEntryColon": {
      "enabled": false
    },
    "SystemExit": {
      "enabled": false
    },
    "UnnecessaryGetter": {
      "enabled": false
    },
    "UnnecessaryObjectReferences": {
      "enabled": false
    },
    "UnnecessarySetter": {
      "enabled": false
    },
    "VariableName": {
      "enabled": false
    },
    "VariableTypeRequired": {
      "enabled": false
    }
  }
}
```

=== Adjustments to `.vscode/settings.json`
Adjust all VsCode/code-server workspace/repository configuration(s) to prevent groovyLint from attempting to enforce indentation rules.

```
  "groovyLint.format.enable": false,
  "groovyLint.format.useDocumentIndentSize": false
```

=== Disabled Default Checks

The type ArrayList should be replaced with an interface or more general parent class::
```
"ImplementationAsType": {
  "enabled": false         // Not possible in a sandboxed environment
},
```

Class should be marked with one of @GrailsCompileStatic, @CompileStatic or @CompileDynamic::
```
"CompileStatic": {
  "enabled": false         // Not possible in a sandboxed environment
},
```

Map [filterEvents:true] is duplicated::
```
"DuplicateMapLiteral": {   // See default treatment for Number and String
  "enabled": false         // No Hubitat static|global alternative
},
```

The statement on line ## ... is at the incorrect indent level ...::
```
"Indentation": {
  "enabled": false         // Conflicts with VsCode
},
```

=== Tolerate Some Noise

Unexpected character: '\#' @ line ##, column 1::
```
"NglParseError": {
  "enabled": true          // Each #include generates a false positive
},
```

=== Pending Review

xxx
TBD

xxx
TBD

xxx
TBD

xxx
TBD

xxx
TBD

xxx
TBD

xxx
TBD

== P A R K E D

Disable linting of functionality that is not possible in Hubitat's sandboxed environment.

```
  "ImplementationAsType": {
    "enabled": false
  },
  "CompileStatic": {
    "enabled": false
  },
  "Indentation": {
    "enabled": false
  },
```

DO NOT disable `NglParseError`. The linter will report `Unexpected character '#'` when a Hubitat App #includes a Hubitat library. Disabling `NglParseError` would be overkill.

```
  "NglParseError": {
    "enabled": true
  },
```

== Command-Line Linting on MacOS

Install Homebrew::
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
Configure Brew in `~/.zprofile`::
```
eval "$(/opt/homebrew/bin/brew shellenv)"
```

Install NVM, Node and Groovy Lint::
```
brew install nvm
nvm install node
npm install -g npm-groovy-lint
```
Command-line Linting::
```
npm-groovy-lint <target file | target directory>
```
